"""Auto-generated by Codegen seeds.
Kind: UseCase
Name: generate_action
"""

from dataclasses import dataclass
from pathlib import Path

from codegen.domain.ports.file_system_port import FileSystemPort
from codegen.domain.ports.template_port import TemplatePort
from codegen.shared.enums import ActionKind, CodeForm
from codegen.domain.value_objects.feature_name import FeatureName


@dataclass(frozen=True)
class GenerateActionCommand:
    """UseCase input."""
    kind: ActionKind
    name: str
    target_root: Path
    form: CodeForm
    with_mapper: bool = False

@dataclass(frozen=True)
class GenerateActionResult:
    """UseCase output."""
    path: Path

@dataclass
class GenerateActionHandler:
    """UseCase handler (application service)."""
    templater: TemplatePort
    file_system: FileSystemPort

    def execute(self, command: GenerateActionCommand) -> GenerateActionResult:
        # 1. 领域对象构建与验证
        feature = FeatureName(command.name)
    
        # 2. 准备上下文 (Context)
        kind_suffix = "Command" if command.kind == "use_case" else "Query"
        ctx = {
            "kind": "UseCase" if command.kind == "use_case" else "Query",
            "name_snake": feature.snake_case,
            "pascal": feature.pascal_case,
            "kind_suffix": kind_suffix,
            "kind_var": "command" if command.kind == "use_case" else "query",
            "with_mapper": command.with_mapper,
        }
    
        # 3. 计算基础路径
        # application/use_cases 或 application/queries
        base_dir_name = "use_cases" if command.kind == "use_case" else "queries"
        base_dir = command.target_root / "application" / base_dir_name
    
        # 确保父级包存在 (application/use_cases/__init__.py)
        self.file_system.ensure_package(base_dir)
    
        # 4. 生成策略分支
        if command.form == "single":
            path = self._generate_single(base_dir, feature, ctx)
        else:
            path = self._generate_package(base_dir, feature, ctx)
        return GenerateActionResult(path=path)
    
    def _generate_single(self, base_dir: Path, feature: FeatureName, ctx: dict) -> Path:
        file_path = base_dir / f"{feature.snake_case}.py"
        content = self.templater.render("application_action/single.py.j2", ctx)
        self.file_system.write_file(file_path, content)
        return file_path
    
    def _generate_package(self, base_dir: Path, feature: FeatureName, ctx: dict) -> Path:
        pkg_dir = base_dir / feature.snake_case
        self.file_system.ensure_package(pkg_dir)
    
        # 定义文件映射关系：模板 -> 目标文件名
        files_to_gen = {
            "pkg_command.py.j2": "command.py",
            "pkg_result.py.j2": "result.py",
            "pkg_handler.py.j2": "handler.py",
            "pkg___init__.py.j2": "__init__.py"
        }
    
        if ctx["with_mapper"]:
            files_to_gen["pkg_mapper.py.j2"] = "mapper.py"

        for tpl_name, file_name in files_to_gen.items():
            content = self.templater.render(f"application_action/{tpl_name}", ctx)
            self.file_system.write_file(pkg_dir / file_name, content)
    
        return pkg_dir