"""Auto-generated by Codegen seeds.
Kind: UseCase
Name: init_project
"""

from dataclasses import dataclass
from pathlib import Path

from src.codegen.domain.ports.file_system_port import FileSystemPort

DDD_DIRS = ("domain", "application", "infrastructure", "interfaces")

@dataclass(frozen=True)
class InitProjectCommand:
    """UseCase input."""
    target_dir: Path
    package_name: str = "codegen"
    use_src_layout: bool = True

@dataclass(frozen=True)
class InitProjectResult:
    """UseCase output."""
    ok: bool = True

@dataclass
class InitProjectHandler:
    """UseCase handler (application service)."""
    fs: FileSystemPort

    def execute(self, command: InitProjectCommand) -> InitProjectResult:
        target = command.target_dir.resolve()
        target.mkdir(parents=True, exist_ok=True)

        # 1) docs
        (target / "docs").mkdir(parents=True, exist_ok=True)

        # 2) src layout + python package root
        if command.use_src_layout:
            pkg_root = target / "src" / command.package_name
        else:
            pkg_root = target / command.package_name

        self.fs.ensure_package(pkg_root)

        # 3) DDD layers
        for d in DDD_DIRS:
            p = pkg_root / d
            self.fs.ensure_package(p)
            
        return InitProjectResult(ok=True)
