from pydantic import Field
from codegen.domain_definition.domain.value_objects.attribute import AttributeSpec
from codegen.shared.domain.services.naming_service import NamingService
from codegen.shared.models import ValueObject
from codegen.domain_definition.domain.enums import ImplementationType


class ImplementationSpec(ValueObject):
    """Specification of an implementation to be generated."""

    implements: str
    kind: ImplementationType
    technology: str
    description: str = Field(default_factory=str)
    attributes: list[AttributeSpec] = Field(default_factory=list)

    @classmethod
    def create(
        cls,
        implements: str,
        kind: ImplementationType | str,
        technology: str,
        description: str = "",
        attributes: list[AttributeSpec] | None = None,
    ):
        if isinstance(kind, str):
            kind = ImplementationType(kind)
        return cls(
            implements=implements,
            kind=kind,
            technology=technology,
            description=description,
            attributes=attributes or [],
        )

    def to_class_name(self) -> str:
        """
        Converts the current instance attributes into a combined class name using camel case formatting for each part.

        This method constructs a string by combining the camel case representations of
        the `technology`, `implements` (with "Port" removed), and the string value of
        the `kind`. The conversion to the camel case is managed by a `NamingService` instance.

        :returns: A string representing a class name generated by combining the relevant
            parts of the instance attributes in camel case format.
        :rtype: str
        """
        naming_service = NamingService()
        parts = [
            naming_service.to_camel_case(self.technology),
            naming_service.to_camel_case(self.implements),
        ]
        return "".join(parts)
